//this file is generated from all the scripts. please check copyright info or license one by one
(function(){function g(a){this.sourceStr=a;this.subCombos=g.parseComboStr(a);this.keyNames=this.subCombos.reduce(function(a,b){return a.concat(b)},[])}function l(a){this.localeName=a;this.pressedKeys=[];this._appliedMacros=[];this._keyMap={};this._killKeyCodes=[];this._macros=[]}function b(a,e,b,m){this._currentContext=this._locale=null;this._contexts={};this._listeners=[];this._appliedListeners=[];this._locales={};this._targetWindow=this._targetElement=null;this._targetUserAgent=this._targetPlatform=
"";this._isModernBrowser=!1;this._targetResetBinding=this._targetKeyUpBinding=this._targetKeyDownBinding=null;this._paused=!1;this.setContext("global");this.watch(a,e,b,m)}var f=window;g.sequenceDeliminator=">>";g.comboDeliminator=">";g.keyDeliminator="+";g.parseComboStr=function(a){a=g._splitStr(a,g.comboDeliminator);for(var e=[],b=0;b<a.length;b+=1)e.push(g._splitStr(a[b],g.keyDeliminator));return e};g.prototype.check=function(a){for(var e=0,b=0;b<this.subCombos.length;b+=1)if(e=this._checkSubCombo(this.subCombos[b],
e,a),-1===e)return!1;return!0};g.prototype.isEqual=function(a){if(!a||"string"!==typeof a&&"object"!==typeof a)return!1;"string"===typeof a&&(a=new g(a));if(this.subCombos.length!==a.subCombos.length)return!1;for(var b=0;b<this.subCombos.length;b+=1)if(this.subCombos[b].length!==a.subCombos[b].length)return!1;for(b=0;b<this.subCombos.length;b+=1){for(var d=this.subCombos[b],m=a.subCombos[b].slice(0),k=0;k<d.length;k+=1){var f=m.indexOf(d[k]);-1<f&&m.splice(f,1)}if(0!==m.length)return!1}return!0};
g._splitStr=function(a,b){for(var e="",m=[],k=0;k<a.length;k+=1)0<k&&a[k]===b&&"\\"!==a[k-1]&&(m.push(e.trim()),e="",k+=1),e+=a[k];e&&m.push(e.trim());return m};g.prototype._checkSubCombo=function(a,b,d){a=a.slice(0);d=d.slice(b);for(var e=0;e<a.length;e+=1){var k=a[e];if("\\"===k[0]){var f=k.slice(1);if(f===g.comboDeliminator||f===g.keyDeliminator)k=f}k=d.indexOf(k);if(-1<k&&(a.splice(e,1),--e,k>b&&(b=k),0===a.length))return b}return-1};l.prototype.bindKeyCode=function(a,b){"string"===typeof b&&
(b=[b]);this._keyMap[a]=b};l.prototype.bindMacro=function(a,b){"string"===typeof b&&(b=[b]);var e=null;"function"===typeof b&&(e=b,b=null);e={keyCombo:new g(a),keyNames:b,handler:e};this._macros.push(e)};l.prototype.getKeyCodes=function(a){var b=[],d;for(d in this._keyMap)-1<this._keyMap[d].indexOf(a)&&b.push(d|0);return b};l.prototype.getKeyNames=function(a){return this._keyMap[a]||[]};l.prototype.setKillKey=function(a){if("string"===typeof a){a=this.getKeyCodes(a);for(var b=0;b<a.length;b+=1)this.setKillKey(a[b])}else this._killKeyCodes.push(a)};
l.prototype.pressKey=function(a){if("string"===typeof a){var b=this.getKeyCodes(a);for(a=0;a<b.length;a+=1)this.pressKey(b[a])}else{b=this.getKeyNames(a);for(a=0;a<b.length;a+=1)-1===this.pressedKeys.indexOf(b[a])&&this.pressedKeys.push(b[a]);this._applyMacros()}};l.prototype.releaseKey=function(a){if("string"===typeof a){var b=this.getKeyCodes(a);for(a=0;a<b.length;a+=1)this.releaseKey(b[a])}else{b=this.getKeyNames(a);if(-1<this._killKeyCodes.indexOf(a))this.pressedKeys.length=0;else for(a=0;a<b.length;a+=
1){var d=this.pressedKeys.indexOf(b[a]);-1<d&&this.pressedKeys.splice(d,1)}this._clearMacros()}};l.prototype._applyMacros=function(){for(var a=this._macros.slice(0),b=0;b<a.length;b+=1){var d=a[b];if(d.keyCombo.check(this.pressedKeys)){d.handler&&(d.keyNames=d.handler(this.pressedKeys));for(var m=0;m<d.keyNames.length;m+=1)-1===this.pressedKeys.indexOf(d.keyNames[m])&&this.pressedKeys.push(d.keyNames[m]);this._appliedMacros.push(d)}}};l.prototype._clearMacros=function(){for(var a=0;a<this._appliedMacros.length;a+=
1){var b=this._appliedMacros[a];if(!b.keyCombo.check(this.pressedKeys)){for(var d=0;d<b.keyNames.length;d+=1){var m=this.pressedKeys.indexOf(b.keyNames[d]);-1<m&&this.pressedKeys.splice(m,1)}b.handler&&(b.keyNames=null);this._appliedMacros.splice(a,1);--a}}};b.prototype.setLocale=function(a,b){var e;"string"===typeof a?b?(e=new l(a),b(e,this._targetPlatform,this._targetUserAgent)):e=this._locales[a]||null:(e=a,a=e._localeName);this._locale=e;if(this._locales[a]=e)this._locale.pressedKeys=e.pressedKeys};
b.prototype.getLocale=function(a){a||(a=this._locale.localeName);return this._locales[a]||null};b.prototype.bind=function(a,b,d,m){if(null===a||"function"===typeof a)m=d,d=b,b=a,a=null;if(a&&"object"===typeof a&&"number"===typeof a.length)for(m=0;m<a.length;m+=1)this.bind(a[m],b,d);else this._listeners.push({keyCombo:a?new g(a):null,pressHandler:b||null,releaseHandler:d||null,preventRepeat:m||!1,preventRepeatByDefault:m||!1})};b.prototype.addListener=b.prototype.bind;b.prototype.on=b.prototype.bind;
b.prototype.unbind=function(a,b,d){if(null===a||"function"===typeof a)d=b,b=a,a=null;if(a&&"object"===typeof a&&"number"===typeof a.length)for(var e=0;e<a.length;e+=1)this.unbind(a[e],b,d);else for(e=0;e<this._listeners.length;e+=1){var k=this._listeners[e],f=!a&&!k.keyCombo||k.keyCombo&&k.keyCombo.isEqual(a),g=!b&&!d||!b&&!k.pressHandler||b===k.pressHandler,k=!b&&!d||!d&&!k.releaseHandler||d===k.releaseHandler;f&&g&&k&&(this._listeners.splice(e,1),--e)}};b.prototype.removeListener=b.prototype.unbind;
b.prototype.off=b.prototype.unbind;b.prototype.setContext=function(a){this._locale&&this.releaseAllKeys();this._contexts[a]||(this._contexts[a]=[]);this._listeners=this._contexts[a];this._currentContext=a};b.prototype.getContext=function(){return this._currentContext};b.prototype.withContext=function(a,b){var e=this.getContext();this.setContext(a);b();this.setContext(e)};b.prototype.watch=function(a,b,d,m){var e=this;this.stop();if(!a){if(!f.addEventListener&&!f.attachEvent)throw Error("Cannot find global functions addEventListener or attachEvent.");
a=f}"number"===typeof a.nodeType&&(m=d,d=b,b=a,a=f);if(!a.addEventListener&&!a.attachEvent)throw Error("Cannot find addEventListener or attachEvent methods on targetWindow.");this._isModernBrowser=!!a.addEventListener;var g=a.navigator&&a.navigator.userAgent||"",l=a.navigator&&a.navigator.platform||"";b&&null!==b||(b=a.document);d&&null!==d||(d=l);m&&null!==m||(m=g);this._targetKeyDownBinding=function(a){e.pressKey(a.keyCode,a)};this._targetKeyUpBinding=function(a){e.releaseKey(a.keyCode,a)};this._targetResetBinding=
function(a){e.releaseAllKeys(a)};this._bindEvent(b,"keydown",this._targetKeyDownBinding);this._bindEvent(b,"keyup",this._targetKeyUpBinding);this._bindEvent(a,"focus",this._targetResetBinding);this._bindEvent(a,"blur",this._targetResetBinding);this._targetElement=b;this._targetWindow=a;this._targetPlatform=d;this._targetUserAgent=m};b.prototype.stop=function(){this._targetElement&&this._targetWindow&&(this._unbindEvent(this._targetElement,"keydown",this._targetKeyDownBinding),this._unbindEvent(this._targetElement,
"keyup",this._targetKeyUpBinding),this._unbindEvent(this._targetWindow,"focus",this._targetResetBinding),this._unbindEvent(this._targetWindow,"blur",this._targetResetBinding),this._targetElement=this._targetWindow=null)};b.prototype.pressKey=function(a,b){if(!this._paused){if(!this._locale)throw Error("Locale not set");this._locale.pressKey(a);this._applyBindings(b)}};b.prototype.releaseKey=function(a,b){if(!this._paused){if(!this._locale)throw Error("Locale not set");this._locale.releaseKey(a);this._clearBindings(b)}};
b.prototype.releaseAllKeys=function(a){if(!this._paused){if(!this._locale)throw Error("Locale not set");this._locale.pressedKeys.length=0;this._clearBindings(a)}};b.prototype.pause=function(){this._paused||(this._locale&&this.releaseAllKeys(),this._paused=!0)};b.prototype.resume=function(){this._paused=!1};b.prototype.reset=function(){this.releaseAllKeys();this._listeners.length=0};b.prototype._bindEvent=function(a,b,d){return this._isModernBrowser?a.addEventListener(b,d,!1):a.attachEvent("on"+b,
d)};b.prototype._unbindEvent=function(a,b,d){return this._isModernBrowser?a.removeEventListener(b,d,!1):a.detachEvent("on"+b,d)};b.prototype._getGroupedListeners=function(){var a=[],b=[],d=this._listeners;"global"!==this._currentContext&&(d=[].concat(d,this._contexts.global));d.sort(function(a,b){return(b.keyCombo?b.keyCombo.keyNames.length:0)-(a.keyCombo?a.keyCombo.keyNames.length:0)}).forEach(function(e){for(var d=-1,f=0;f<b.length;f+=1)if(null===b[f]&&null===e.keyCombo||null!==b[f]&&b[f].isEqual(e.keyCombo))d=
f;-1===d&&(d=b.length,b.push(e.keyCombo));a[d]||(a[d]=[]);a[d].push(e)});return a};b.prototype._applyBindings=function(a){var b=!1;a||(a={});a.preventRepeat=function(){b=!0};a.pressedKeys=this._locale.pressedKeys.slice(0);for(var d=this._locale.pressedKeys.slice(0),f=this._getGroupedListeners(),k=0;k<f.length;k+=1){var l=f[k],z=l[0].keyCombo;if(null===z||z.check(d)){for(var u=0;u<l.length;u+=1){var t=l[u];null===z&&(t={keyCombo:new g(d.join("+")),pressHandler:t.pressHandler,releaseHandler:t.releaseHandler,
preventRepeat:t.preventRepeat,preventRepeatByDefault:t.preventRepeatByDefault});t.pressHandler&&!t.preventRepeat&&(t.pressHandler.call(this,a),b&&(t.preventRepeat=b,b=!1));t.releaseHandler&&-1===this._appliedListeners.indexOf(t)&&this._appliedListeners.push(t)}if(z)for(u=0;u<z.keyNames.length;u+=1)l=d.indexOf(z.keyNames[u]),-1!==l&&(d.splice(l,1),--u)}}};b.prototype._clearBindings=function(a){a||(a={});for(var b=0;b<this._appliedListeners.length;b+=1){var d=this._appliedListeners[b],f=d.keyCombo;
null!==f&&f.check(this._locale.pressedKeys)||(d.preventRepeat=d.preventRepeatByDefault,d.releaseHandler.call(this,a),this._appliedListeners.splice(b,1),--b)}};window.keyboard=new b;window.keyboard.setLocale("us",function(a,b,d){a.bindKeyCode(3,["cancel"]);a.bindKeyCode(8,["backspace"]);a.bindKeyCode(9,["tab"]);a.bindKeyCode(12,["clear"]);a.bindKeyCode(13,["enter"]);a.bindKeyCode(16,["shift"]);a.bindKeyCode(17,["ctrl"]);a.bindKeyCode(18,["alt","menu"]);a.bindKeyCode(19,["pause","break"]);a.bindKeyCode(20,
["capslock"]);a.bindKeyCode(27,["escape","esc"]);a.bindKeyCode(32,["space","spacebar"]);a.bindKeyCode(33,["pageup"]);a.bindKeyCode(34,["pagedown"]);a.bindKeyCode(35,["end"]);a.bindKeyCode(36,["home"]);a.bindKeyCode(37,["left"]);a.bindKeyCode(38,["up"]);a.bindKeyCode(39,["right"]);a.bindKeyCode(40,["down"]);a.bindKeyCode(41,["select"]);a.bindKeyCode(42,["printscreen"]);a.bindKeyCode(43,["execute"]);a.bindKeyCode(44,["snapshot"]);a.bindKeyCode(45,["insert","ins"]);a.bindKeyCode(46,["delete","del"]);
a.bindKeyCode(47,["help"]);a.bindKeyCode(145,["scrolllock","scroll"]);a.bindKeyCode(187,["equal","equalsign","="]);a.bindKeyCode(188,["comma",","]);a.bindKeyCode(190,["period","."]);a.bindKeyCode(191,["slash","forwardslash","/"]);a.bindKeyCode(192,["graveaccent","`"]);a.bindKeyCode(219,["openbracket","["]);a.bindKeyCode(220,["backslash","\\"]);a.bindKeyCode(221,["closebracket","]"]);a.bindKeyCode(222,["apostrophe","'"]);a.bindKeyCode(48,["zero","0"]);a.bindKeyCode(49,["one","1"]);a.bindKeyCode(50,
["two","2"]);a.bindKeyCode(51,["three","3"]);a.bindKeyCode(52,["four","4"]);a.bindKeyCode(53,["five","5"]);a.bindKeyCode(54,["six","6"]);a.bindKeyCode(55,["seven","7"]);a.bindKeyCode(56,["eight","8"]);a.bindKeyCode(57,["nine","9"]);a.bindKeyCode(96,["numzero","num0"]);a.bindKeyCode(97,["numone","num1"]);a.bindKeyCode(98,["numtwo","num2"]);a.bindKeyCode(99,["numthree","num3"]);a.bindKeyCode(100,["numfour","num4"]);a.bindKeyCode(101,["numfive","num5"]);a.bindKeyCode(102,["numsix","num6"]);a.bindKeyCode(103,
["numseven","num7"]);a.bindKeyCode(104,["numeight","num8"]);a.bindKeyCode(105,["numnine","num9"]);a.bindKeyCode(106,["nummultiply","num*"]);a.bindKeyCode(107,["numadd","num+"]);a.bindKeyCode(108,["numenter"]);a.bindKeyCode(109,["numsubtract","num-"]);a.bindKeyCode(110,["numdecimal","num."]);a.bindKeyCode(111,["numdivide","num/"]);a.bindKeyCode(144,["numlock","num"]);a.bindKeyCode(112,["f1"]);a.bindKeyCode(113,["f2"]);a.bindKeyCode(114,["f3"]);a.bindKeyCode(115,["f4"]);a.bindKeyCode(116,["f5"]);a.bindKeyCode(117,
["f6"]);a.bindKeyCode(118,["f7"]);a.bindKeyCode(119,["f8"]);a.bindKeyCode(120,["f9"]);a.bindKeyCode(121,["f10"]);a.bindKeyCode(122,["f11"]);a.bindKeyCode(123,["f12"]);a.bindMacro("shift + `",["tilde","~"]);a.bindMacro("shift + 1",["exclamation","exclamationpoint","!"]);a.bindMacro("shift + 2",["at","@"]);a.bindMacro("shift + 3",["number","#"]);a.bindMacro("shift + 4",["dollar","dollars","dollarsign","$"]);a.bindMacro("shift + 5",["percent","%"]);a.bindMacro("shift + 6",["caret","^"]);a.bindMacro("shift + 7",
["ampersand","and","&"]);a.bindMacro("shift + 8",["asterisk","*"]);a.bindMacro("shift + 9",["openparen","("]);a.bindMacro("shift + 0",["closeparen",")"]);a.bindMacro("shift + -",["underscore","_"]);a.bindMacro("shift + =",["plus","+"]);a.bindMacro("shift + [",["opencurlybrace","opencurlybracket","{"]);a.bindMacro("shift + ]",["closecurlybrace","closecurlybracket","}"]);a.bindMacro("shift + \\",["verticalbar","|"]);a.bindMacro("shift + ;",["colon",":"]);a.bindMacro("shift + '",["quotationmark","'"]);
a.bindMacro("shift + !,",["openanglebracket","<"]);a.bindMacro("shift + .",["closeanglebracket",">"]);a.bindMacro("shift + /",["questionmark","?"]);for(var f=65;90>=f;f+=1){var e=String.fromCharCode(f+32),g=String.fromCharCode(f);a.bindKeyCode(f,e);a.bindMacro("shift + "+e,g);a.bindMacro("capslock + "+e,g)}var f=d.match("Firefox")?59:186,e=d.match("Firefox")?173:189,l,u;b.match("Mac")&&(d.match("Safari")||d.match("Chrome"))?(l=91,u=93):b.match("Mac")&&d.match("Opera")?u=l=17:b.match("Mac")&&d.match("Firefox")&&
(u=l=224);a.bindKeyCode(f,["semicolon",";"]);a.bindKeyCode(e,["dash","-"]);a.bindKeyCode(l,"command windows win super leftcommand leftwindows leftwin leftsuper".split(" "));a.bindKeyCode(u,"command windows win super rightcommand rightwindows rightwin rightsuper".split(" "));a.setKillKey("command")})})();
(function(g,l,b,f){function a(c,a,b){return setTimeout(J(c,b),a)}function e(c,a,b){return Array.isArray(c)?(d(c,b[a],b),!0):!1}function d(c,a,b){var h;if(c)if(c.forEach)c.forEach(a,b);else if(c.length!==f)for(h=0;h<c.length;)a.call(b,c[h],h,c),h++;else for(h in c)c.hasOwnProperty(h)&&a.call(b,c[h],h,c)}function m(c,a,b){var h="DEPRECATED METHOD: "+a+"\n"+b+" AT \n";return function(){var a=Error("get-stack-trace"),a=a&&a.stack?a.stack.replace(/^[^\(]+?[\n$]/gm,"").replace(/^\s+at\s+/gm,"").replace(/^Object.<anonymous>\s*\(/gm,
"{anonymous}()@"):"Unknown Stack Trace",b=g.console&&(g.console.warn||g.console.log);b&&b.call(g.console,h,a);return c.apply(this,arguments)}}function k(c,a,b){a=a.prototype;var h;h=c.prototype=Object.create(a);h.constructor=c;h._super=a;b&&O(h,b)}function J(c,a){return function(){return c.apply(a,arguments)}}function z(c,a){return"function"==typeof c?c.apply(a?a[0]||f:f,a):c}function u(c,a,b){d(V(a),function(a){c.addEventListener(a,b,!1)})}function t(c,a,b){d(V(a),function(a){c.removeEventListener(a,
b,!1)})}function la(c,a){for(;c;){if(c==a)return!0;c=c.parentNode}return!1}function V(c){return c.trim().split(/\s+/g)}function P(c,a,b){if(c.indexOf&&!b)return c.indexOf(a);for(var h=0;h<c.length;){if(b&&c[h][b]==a||!b&&c[h]===a)return h;h++}return-1}function C(c){return Array.prototype.slice.call(c,0)}function ma(c,a,b){for(var h=[],n=[],d=0;d<c.length;){var f=a?c[d][a]:c[d];0>P(n,f)&&h.push(c[d]);n[d]=f;d++}b&&(h=a?h.sort(function(c,b){return c[a]>b[a]}):h.sort());return h}function W(c,a){for(var b,
h=a[0].toUpperCase()+a.slice(1),d=0;d<na.length;){b=(b=na[d])?b+h:a;if(b in c)return b;d++}return f}function ba(c){c=c.ownerDocument||c;return c.defaultView||c.parentWindow||g}function x(c,a){var b=this;this.manager=c;this.callback=a;this.element=c.element;this.target=c.options.inputTarget;this.domHandler=function(a){z(c.options.enable,[c])&&b.handler(a)};this.init()}function fa(c){var a=c.options.inputClass;return new (a?a:wa?D:xa?L:oa?X:G)(c,E)}function E(c,a,b){var h,n,d=b.pointers.length,e=b.changedPointers.length;
h=a&1&&0===d-e;b.isFirst=!!h;b.isFinal=!!(a&12&&0===d-e);h&&(c.session={});b.eventType=a;a=c.session;d=b.pointers;e=d.length;a.firstInput||(a.firstInput=S(b));1<e&&!a.firstMultiple?a.firstMultiple=S(b):1===e&&(a.firstMultiple=!1);h=a.firstInput;n=(e=a.firstMultiple)?e.center:h.center;var g=b.center=M(d);b.timeStamp=ka();b.deltaTime=b.timeStamp-h.timeStamp;b.angle=p(n,g);b.distance=T(n,g);h=b.center;n=a.offsetDelta||{};var g=a.prevDelta||{},k=a.prevInput||{};if(1===b.eventType||4===k.eventType)g=a.prevDelta=
{x:k.deltaX||0,y:k.deltaY||0},n=a.offsetDelta={x:h.x,y:h.y};b.deltaX=g.x+(h.x-n.x);b.deltaY=g.y+(h.y-n.y);b.offsetDirection=Y(b.deltaX,b.deltaY);n=b.deltaTime;h=b.deltaX/n||0;n=b.deltaY/n||0;b.overallVelocityX=h;b.overallVelocityY=n;b.overallVelocity=Q(h)>Q(n)?h:n;e?(h=e.pointers,h=T(d[0],d[1],ga)/T(h[0],h[1],ga)):h=1;b.scale=h;e?(e=e.pointers,d=p(d[1],d[0],ga)+p(e[1],e[0],ga)):d=0;b.rotation=d;b.maxPointers=a.prevInput?b.pointers.length>a.prevInput.maxPointers?b.pointers.length:a.prevInput.maxPointers:
b.pointers.length;n=a.lastInterval||b;d=b.timeStamp-n.timeStamp;8!=b.eventType&&(25<d||n.velocity===f)?(h=b.deltaX-n.deltaX,n=b.deltaY-n.deltaY,g=h/d||0,k=n/d||0,d=g,e=k,g=Q(g)>Q(k)?g:k,h=Y(h,n),a.lastInterval=b):(g=n.velocity,d=n.velocityX,e=n.velocityY,h=n.direction);b.velocity=g;b.velocityX=d;b.velocityY=e;b.direction=h;a=c.element;la(b.srcEvent.target,a)&&(a=b.srcEvent.target);b.target=a;c.emit("hammer.input",b);c.recognize(b);c.session.prevInput=b}function S(a){for(var c=[],b=0;b<a.pointers.length;)c[b]=
{clientX:Z(a.pointers[b].clientX),clientY:Z(a.pointers[b].clientY)},b++;return{timeStamp:ka(),pointers:c,center:M(c),deltaX:a.deltaX,deltaY:a.deltaY}}function M(a){var b=a.length;if(1===b)return{x:Z(a[0].clientX),y:Z(a[0].clientY)};for(var c=0,d=0,e=0;e<b;)c+=a[e].clientX,d+=a[e].clientY,e++;return{x:Z(c/b),y:Z(d/b)}}function Y(a,b){return a===b?1:Q(a)>=Q(b)?0>a?2:4:0>b?8:16}function T(a,b,n){n||(n=pa);var c=b[n[0]]-a[n[0]];a=b[n[1]]-a[n[1]];return Math.sqrt(c*c+a*a)}function p(a,b,n){n||(n=pa);return 180*
Math.atan2(b[n[1]]-a[n[1]],b[n[0]]-a[n[0]])/Math.PI}function G(){this.evEl=ya;this.evWin=za;this.pressed=!1;x.apply(this,arguments)}function D(){this.evEl=qa;this.evWin=ra;x.apply(this,arguments);this.store=this.manager.session.pointerEvents=[]}function H(){this.evTarget="touchstart";this.evWin="touchstart touchmove touchend touchcancel";this.started=!1;x.apply(this,arguments)}function L(){this.evTarget=Aa;this.targetIds={};x.apply(this,arguments)}function ca(a,b){var c=C(a.touches),h=this.targetIds;
if(b&3&&1===c.length)return h[c[0].identifier]=!0,[c,c];var d,e=C(a.changedTouches),f=[],g=this.target;d=c.filter(function(a){return la(a.target,g)});if(1===b)for(c=0;c<d.length;)h[d[c].identifier]=!0,c++;for(c=0;c<e.length;)h[e[c].identifier]&&f.push(e[c]),b&12&&delete h[e[c].identifier],c++;if(f.length)return[ma(d.concat(f),"identifier",!0),f]}function X(){x.apply(this,arguments);var a=J(this.handler,this);this.touch=new L(this.manager,a);this.mouse=new G(this.manager,a);this.primaryTouch=null;
this.lastTouches=[]}function ha(a){a=a.changedPointers[0];if(a.identifier===this.primaryTouch){var b={x:a.clientX,y:a.clientY};this.lastTouches.push(b);var c=this.lastTouches;setTimeout(function(){var a=c.indexOf(b);-1<a&&c.splice(a,1)},2500)}}function da(a,b){this.manager=a;this.set(b)}function U(a){if(-1<a.indexOf("none"))return"none";var b=-1<a.indexOf("pan-x"),c=-1<a.indexOf("pan-y");return b&&c?"none":b||c?b?"pan-x":"pan-y":-1<a.indexOf("manipulation")?"manipulation":"auto"}function A(a){this.options=
O({},this.defaults,a||{});this.id=Ba++;this.manager=null;a=this.options.enable;this.options.enable=a===f?!0:a;this.state=1;this.simultaneous={};this.requireFail=[]}function sa(a){return a&16?"cancel":a&8?"end":a&4?"move":a&2?"start":""}function aa(a){return 16==a?"down":8==a?"up":2==a?"left":4==a?"right":""}function r(a,b){var c=b.manager;return c?c.get(a):a}function q(){A.apply(this,arguments)}function ia(){q.apply(this,arguments);this.pY=this.pX=null}function w(){q.apply(this,arguments)}function N(){A.apply(this,
arguments);this._input=this._timer=null}function K(){q.apply(this,arguments)}function I(){q.apply(this,arguments)}function B(){A.apply(this,arguments);this.pCenter=this.pTime=!1;this._input=this._timer=null;this.count=0}function v(a,b){b=b||{};var c=b.recognizers;b.recognizers=c===f?v.defaults.preset:c;return new y(a,b)}function y(a,b){this.options=O({},v.defaults,b||{});this.options.inputTarget=this.options.inputTarget||a;this.handlers={};this.session={};this.recognizers=[];this.oldCssProps={};this.element=
a;this.input=fa(this);this.touchAction=new da(this,this.options.touchAction);R(this,!0);d(this.options.recognizers,function(a){var b=this.add(new a[0](a[1]));a[2]&&b.recognizeWith(a[2]);a[3]&&b.requireFailure(a[3])},this)}function R(a,b){var c=a.element;if(c.style){var h;d(a.options.cssProps,function(n,d){h=W(c.style,d);b?(a.oldCssProps[h]=c.style[h],c.style[h]=n):c.style[h]=a.oldCssProps[h]||""});b||(a.oldCssProps={})}}function F(a,b){var c=l.createEvent("Event");c.initEvent(a,!0,!0);c.gesture=b;
b.target.dispatchEvent(c)}var na=" webkit Moz MS ms o".split(" "),ea=l.createElement("div"),Z=Math.round,Q=Math.abs,ka=Date.now,O;O="function"!==typeof Object.assign?function(a){if(a===f||null===a)throw new TypeError("Cannot convert undefined or null to object");for(var b=Object(a),c=1;c<arguments.length;c++){var d=arguments[c];if(d!==f&&null!==d)for(var e in d)d.hasOwnProperty(e)&&(b[e]=d[e])}return b}:Object.assign;var ta=m(function(a,b,d){for(var c=Object.keys(b),h=0;h<c.length;){if(!d||d&&a[c[h]]===
f)a[c[h]]=b[c[h]];h++}return a},"extend","Use `assign`."),Ca=m(function(a,b){return ta(a,b,!0)},"merge","Use `assign`."),Ba=1,Da=/mobile|tablet|ip(ad|hone|od)|android/i,oa="ontouchstart"in g,wa=W(g,"PointerEvent")!==f,xa=oa&&Da.test(navigator.userAgent),pa=["x","y"],ga=["clientX","clientY"];x.prototype={handler:function(){},init:function(){this.evEl&&u(this.element,this.evEl,this.domHandler);this.evTarget&&u(this.target,this.evTarget,this.domHandler);this.evWin&&u(ba(this.element),this.evWin,this.domHandler)},
destroy:function(){this.evEl&&t(this.element,this.evEl,this.domHandler);this.evTarget&&t(this.target,this.evTarget,this.domHandler);this.evWin&&t(ba(this.element),this.evWin,this.domHandler)}};var Ea={mousedown:1,mousemove:2,mouseup:4},ya="mousedown",za="mousemove mouseup";k(G,x,{handler:function(a){var b=Ea[a.type];b&1&&0===a.button&&(this.pressed=!0);b&2&&1!==a.which&&(b=4);this.pressed&&(b&4&&(this.pressed=!1),this.callback(this.manager,b,{pointers:[a],changedPointers:[a],pointerType:"mouse",srcEvent:a}))}});
var Fa={pointerdown:1,pointermove:2,pointerup:4,pointercancel:8,pointerout:8},Ga={2:"touch",3:"pen",4:"mouse",5:"kinect"},qa="pointerdown",ra="pointermove pointerup pointercancel";g.MSPointerEvent&&!g.PointerEvent&&(qa="MSPointerDown",ra="MSPointerMove MSPointerUp MSPointerCancel");k(D,x,{handler:function(a){var b=this.store,c=!1,d=a.type.toLowerCase().replace("ms",""),d=Fa[d],e=Ga[a.pointerType]||a.pointerType,f="touch"==e,g=P(b,a.pointerId,"pointerId");d&1&&(0===a.button||f)?0>g&&(b.push(a),g=b.length-
1):d&12&&(c=!0);0>g||(b[g]=a,this.callback(this.manager,d,{pointers:b,changedPointers:[a],pointerType:e,srcEvent:a}),c&&b.splice(g,1))}});var Ha={touchstart:1,touchmove:2,touchend:4,touchcancel:8};k(H,x,{handler:function(a){var b=Ha[a.type];1===b&&(this.started=!0);if(this.started){var c;c=C(a.touches);var d=C(a.changedTouches);b&12&&(c=ma(c.concat(d),"identifier",!0));c=[c,d];b&12&&0===c[0].length-c[1].length&&(this.started=!1);this.callback(this.manager,b,{pointers:c[0],changedPointers:c[1],pointerType:"touch",
srcEvent:a})}}});var Ia={touchstart:1,touchmove:2,touchend:4,touchcancel:8},Aa="touchstart touchmove touchend touchcancel";k(L,x,{handler:function(a){var b=Ia[a.type],c=ca.call(this,a,b);c&&this.callback(this.manager,b,{pointers:c[0],changedPointers:c[1],pointerType:"touch",srcEvent:a})}});k(X,x,{handler:function(a,b,d){var c="mouse"==d.pointerType;if(!(c&&d.sourceCapabilities&&d.sourceCapabilities.firesTouchEvents)){if("touch"==d.pointerType)b&1?(this.primaryTouch=d.changedPointers[0].identifier,
ha.call(this,d)):b&12&&ha.call(this,d);else{if(c)a:{for(var c=d.srcEvent.clientX,h=d.srcEvent.clientY,e=0;e<this.lastTouches.length;e++){var f=this.lastTouches[e],n=Math.abs(h-f.y);if(25>=Math.abs(c-f.x)&&25>=n){c=!0;break a}}c=!1}if(c)return}this.callback(a,b,d)}},destroy:function(){this.touch.destroy();this.mouse.destroy()}});var ua=W(ea.style,"touchAction"),va=ua!==f,ja=function(){if(!va)return!1;var a={},b=g.CSS&&g.CSS.supports;"auto;manipulation;pan-y;pan-x;pan-x pan-y;none".split(";").forEach(function(c){a[c]=
b?g.CSS.supports("touch-action",c):!0});return a}();da.prototype={set:function(a){"compute"==a&&(a=this.compute());va&&this.manager.element.style&&ja[a]&&(this.manager.element.style[ua]=a);this.actions=a.toLowerCase().trim()},update:function(){this.set(this.manager.options.touchAction)},compute:function(){var a=[];d(this.manager.recognizers,function(b){z(b.options.enable,[b])&&(a=a.concat(b.getTouchAction()))});return U(a.join(" "))},preventDefaults:function(a){var b=a.srcEvent,c=a.offsetDirection;
if(this.manager.session.prevented)b.preventDefault();else{var d=this.actions,e=-1<d.indexOf("none")&&!ja.none,f=-1<d.indexOf("pan-y")&&!ja["pan-y"],d=-1<d.indexOf("pan-x")&&!ja["pan-x"];if(e){var g=2>a.distance,k=250>a.deltaTime;if(1===a.pointers.length&&g&&k)return}if(!d||!f)if(e||f&&c&6||d&&c&24)return this.preventSrc(b)}},preventSrc:function(a){this.manager.session.prevented=!0;a.preventDefault()}};A.prototype={defaults:{},set:function(a){O(this.options,a);this.manager&&this.manager.touchAction.update();
return this},recognizeWith:function(a){if(e(a,"recognizeWith",this))return this;var b=this.simultaneous;a=r(a,this);b[a.id]||(b[a.id]=a,a.recognizeWith(this));return this},dropRecognizeWith:function(a){if(e(a,"dropRecognizeWith",this))return this;a=r(a,this);delete this.simultaneous[a.id];return this},requireFailure:function(a){if(e(a,"requireFailure",this))return this;var b=this.requireFail;a=r(a,this);-1===P(b,a)&&(b.push(a),a.requireFailure(this));return this},dropRequireFailure:function(a){if(e(a,
"dropRequireFailure",this))return this;a=r(a,this);a=P(this.requireFail,a);-1<a&&this.requireFail.splice(a,1);return this},hasRequireFailures:function(){return 0<this.requireFail.length},canRecognizeWith:function(a){return!!this.simultaneous[a.id]},emit:function(a){function b(b){c.manager.emit(b,a)}var c=this,d=this.state;8>d&&b(c.options.event+sa(d));b(c.options.event);a.additionalEvent&&b(a.additionalEvent);8<=d&&b(c.options.event+sa(d))},tryEmit:function(a){if(this.canEmit())return this.emit(a);
this.state=32},canEmit:function(){for(var a=0;a<this.requireFail.length;){if(!(this.requireFail[a].state&33))return!1;a++}return!0},recognize:function(a){a=O({},a);z(this.options.enable,[this,a])?(this.state&56&&(this.state=1),this.state=this.process(a),this.state&30&&this.tryEmit(a)):(this.reset(),this.state=32)},process:function(a){},getTouchAction:function(){},reset:function(){}};k(q,A,{defaults:{pointers:1},attrTest:function(a){var b=this.options.pointers;return 0===b||a.pointers.length===b},
process:function(a){var b=this.state,c=a.eventType,d=b&6;a=this.attrTest(a);return d&&(c&8||!a)?b|16:d||a?c&4?b|8:b&2?b|4:2:32}});k(ia,q,{defaults:{event:"pan",threshold:10,pointers:1,direction:30},getTouchAction:function(){var a=this.options.direction,b=[];a&6&&b.push("pan-y");a&24&&b.push("pan-x");return b},directionTest:function(a){var b=this.options,c=!0,d=a.distance,e=a.direction,f=a.deltaX,g=a.deltaY;e&b.direction||(b.direction&6?(e=0===f?1:0>f?2:4,c=f!=this.pX,d=Math.abs(a.deltaX)):(e=0===
g?1:0>g?8:16,c=g!=this.pY,d=Math.abs(a.deltaY)));a.direction=e;return c&&d>b.threshold&&e&b.direction},attrTest:function(a){return q.prototype.attrTest.call(this,a)&&(this.state&2||!(this.state&2)&&this.directionTest(a))},emit:function(a){this.pX=a.deltaX;this.pY=a.deltaY;var b=aa(a.direction);b&&(a.additionalEvent=this.options.event+b);this._super.emit.call(this,a)}});k(w,q,{defaults:{event:"pinch",threshold:0,pointers:2},getTouchAction:function(){return["none"]},attrTest:function(a){return this._super.attrTest.call(this,
a)&&(Math.abs(a.scale-1)>this.options.threshold||this.state&2)},emit:function(a){1!==a.scale&&(a.additionalEvent=this.options.event+(1>a.scale?"in":"out"));this._super.emit.call(this,a)}});k(N,A,{defaults:{event:"press",pointers:1,time:251,threshold:9},getTouchAction:function(){return["auto"]},process:function(b){var c=this.options,d=b.pointers.length===c.pointers,e=b.distance<c.threshold,f=b.deltaTime>c.time;this._input=b;if(!e||!d||b.eventType&12&&!f)this.reset();else if(b.eventType&1)this.reset(),
this._timer=a(function(){this.state=8;this.tryEmit()},c.time,this);else if(b.eventType&4)return 8;return 32},reset:function(){clearTimeout(this._timer)},emit:function(a){8===this.state&&(a&&a.eventType&4?this.manager.emit(this.options.event+"up",a):(this._input.timeStamp=ka(),this.manager.emit(this.options.event,this._input)))}});k(K,q,{defaults:{event:"rotate",threshold:0,pointers:2},getTouchAction:function(){return["none"]},attrTest:function(a){return this._super.attrTest.call(this,a)&&(Math.abs(a.rotation)>
this.options.threshold||this.state&2)}});k(I,q,{defaults:{event:"swipe",threshold:10,velocity:.3,direction:30,pointers:1},getTouchAction:function(){return ia.prototype.getTouchAction.call(this)},attrTest:function(a){var b=this.options.direction,c;b&30?c=a.overallVelocity:b&6?c=a.overallVelocityX:b&24&&(c=a.overallVelocityY);return this._super.attrTest.call(this,a)&&b&a.offsetDirection&&a.distance>this.options.threshold&&a.maxPointers==this.options.pointers&&Q(c)>this.options.velocity&&a.eventType&
4},emit:function(a){var b=aa(a.offsetDirection);b&&this.manager.emit(this.options.event+b,a);this.manager.emit(this.options.event,a)}});k(B,A,{defaults:{event:"tap",pointers:1,taps:1,interval:300,time:250,threshold:9,posThreshold:10},getTouchAction:function(){return["manipulation"]},process:function(b){var c=this.options,d=b.pointers.length===c.pointers,e=b.distance<c.threshold,f=b.deltaTime<c.time;this.reset();if(b.eventType&1&&0===this.count)return this.failTimeout();if(e&&f&&d){if(4!=b.eventType)return this.failTimeout();
d=this.pTime?b.timeStamp-this.pTime<c.interval:!0;e=!this.pCenter||T(this.pCenter,b.center)<c.posThreshold;this.pTime=b.timeStamp;this.pCenter=b.center;this.count=e&&d?this.count+1:1;this._input=b;if(0===this.count%c.taps)return this.hasRequireFailures()?(this._timer=a(function(){this.state=8;this.tryEmit()},c.interval,this),2):8}return 32},failTimeout:function(){this._timer=a(function(){this.state=32},this.options.interval,this);return 32},reset:function(){clearTimeout(this._timer)},emit:function(){8==
this.state&&(this._input.tapCount=this.count,this.manager.emit(this.options.event,this._input))}});v.VERSION="2.0.7";v.defaults={domEvents:!1,touchAction:"compute",enable:!0,inputTarget:null,inputClass:null,preset:[[K,{enable:!1}],[w,{enable:!1},["rotate"]],[I,{direction:6}],[ia,{direction:6},["swipe"]],[B],[B,{event:"doubletap",taps:2},["tap"]],[N]],cssProps:{userSelect:"none",touchSelect:"none",touchCallout:"none",contentZooming:"none",userDrag:"none",tapHighlightColor:"rgba(0,0,0,0)"}};y.prototype=
{set:function(a){O(this.options,a);a.touchAction&&this.touchAction.update();a.inputTarget&&(this.input.destroy(),this.input.target=a.inputTarget,this.input.init());return this},stop:function(a){this.session.stopped=a?2:1},recognize:function(a){var b=this.session;if(!b.stopped){this.touchAction.preventDefaults(a);var c,d=this.recognizers,e=b.curRecognizer;if(!e||e&&e.state&8)e=b.curRecognizer=null;for(var f=0;f<d.length;)c=d[f],2===b.stopped||e&&c!=e&&!c.canRecognizeWith(e)?c.reset():c.recognize(a),
!e&&c.state&14&&(e=b.curRecognizer=c),f++}},get:function(a){if(a instanceof A)return a;for(var b=this.recognizers,c=0;c<b.length;c++)if(b[c].options.event==a)return b[c];return null},add:function(a){if(e(a,"add",this))return this;var b=this.get(a.options.event);b&&this.remove(b);this.recognizers.push(a);a.manager=this;this.touchAction.update();return a},remove:function(a){if(e(a,"remove",this))return this;if(a=this.get(a)){var b=this.recognizers;a=P(b,a);-1!==a&&(b.splice(a,1),this.touchAction.update())}return this},
on:function(a,b){if(a!==f&&b!==f){var c=this.handlers;d(V(a),function(a){c[a]=c[a]||[];c[a].push(b)});return this}},off:function(a,b){if(a!==f){var c=this.handlers;d(V(a),function(a){b?c[a]&&c[a].splice(P(c[a],b),1):delete c[a]});return this}},emit:function(a,b){this.options.domEvents&&F(a,b);var c=this.handlers[a]&&this.handlers[a].slice();if(c&&c.length){b.type=a;b.preventDefault=function(){b.srcEvent.preventDefault()};for(var d=0;d<c.length;)c[d](b),d++}},destroy:function(){this.element&&R(this,
!1);this.handlers={};this.session={};this.input.destroy();this.element=null}};O(v,{INPUT_START:1,INPUT_MOVE:2,INPUT_END:4,INPUT_CANCEL:8,STATE_POSSIBLE:1,STATE_BEGAN:2,STATE_CHANGED:4,STATE_ENDED:8,STATE_RECOGNIZED:8,STATE_CANCELLED:16,STATE_FAILED:32,DIRECTION_NONE:1,DIRECTION_LEFT:2,DIRECTION_RIGHT:4,DIRECTION_UP:8,DIRECTION_DOWN:16,DIRECTION_HORIZONTAL:6,DIRECTION_VERTICAL:24,DIRECTION_ALL:30,Manager:y,Input:x,TouchAction:da,TouchInput:L,MouseInput:G,PointerEventInput:D,TouchMouseInput:X,SingleTouchInput:H,
Recognizer:A,AttrRecognizer:q,Tap:B,Pan:ia,Swipe:I,Pinch:w,Rotate:K,Press:N,on:u,off:t,each:d,merge:Ca,extend:ta,assign:O,inherit:k,bindFn:J,prefixed:W});("undefined"!==typeof g?g:"undefined"!==typeof self?self:{}).Hammer=v;"function"===typeof define&&define.amd?define(function(){return v}):"undefined"!=typeof module&&module.exports?module.exports=v:g[b]=v})(window,document,"Hammer");
var pygame={init:function(){var g=this;this.Surface=function(b){this.width=b[0];this.height=b[1];this.canvas=document.createElement("canvas");this.canvas.width=this.width;this.canvas.height=this.height;this.context=this.canvas.getContext("2d")};this.Surface.prototype.blit=function(b,f){b instanceof g.fontFakeSurface?b.drawText(this,f):b instanceof g.Surface?this.context.drawImage(b.canvas,Math.round(f[0]),Math.round(f[1])):this.context.drawImage(b,Math.round(f[0]),Math.round(f[1]))};this.Surface.prototype.fill=
function(b){this.context.fillStyle="rgb("+b[0]+","+b[1]+","+b[2]+")";this.context.fillRect(0,0,Math.round(this.width),Math.round(this.height))};this.Surface.prototype.get_rect=function(){var b=[0,0,this.width,this.height];b.left=b[0];b.top=b[1];b.right=b[2];b.bottom=b[3];return b};this.Image=function(b){g.Surface.call(this,[b.width,b.height]);this.blit(b,[0,0])};this.Image.prototype=this.Surface.prototype;this.image={load:function(b,f){var a=new Image;a.src=b;a.alt="";a.onload=function(){var b=new g.Image(a);
f(b)}}};var l;this.display={update:function(){},set_mode:function(b){b=new g.Surface(b);document.body.appendChild(b.canvas);return l=b},resize:function(b){l.canvas.width=b[0];l.canvas.height=b[1];l.width=b[0];l.height=b[1]}};this.time={wait:function(b,f){setTimeout(f,b)},Clock:function(){this.lastCall=0;this.time_list=[]}};this.time.Clock.prototype.tick60=function(b){var f=this;requestAnimationFrame(function(){f.lastCall=Date.now();f.time_list.push(f.lastCall);0<f.time_list.length-10&&f.time_list.splice(0,
f.time_list.length-10);b()})};this.time.Clock.prototype.tick=function(b,f){if(60==b)return this.tick60(f);var a=Date.now(),e=this;setTimeout(function(){e.lastCall=Date.now();e.time_list.push(e.lastCall);0<e.time_list.length-10&&e.time_list.splice(0,e.time_list.length-10);f()},0==this.lastCall?1E3/b:1E3/b-(a-this.lastCall))};this.time.Clock.prototype.get_fps=function(){for(var b=0,f=1;f<this.time_list.length;++f)b+=this.time_list[f]-this.time_list[f-1];b/=this.time_list.length-1;return 1E3/b};"object"!=
typeof this.event&&(this.event=[]);this.event.get=function(){for(var b=[];this.length;)b.push(this.shift());return b};this.font={Font:function(b,f){this.name=b;this.size=f}};this.font.Font.prototype.render=function(b,f,a,e){b=new g.fontFakeSurface(this.name,this.size,b,f,a,e);f=b.get_rect();f=new g.Surface([f.right,f.bottom]);b.drawText(f,[0,0]);return f};this.fontFakeSurface=function(b,f,a,e,d,g){this.name=b;this.size=f;this.text=a;this.msaa=e;this.color=d;this.bgcolor=g};this.fontFakeSurface.prototype.drawText=
function(b,f){b.context.font=null==this.name?this.size+"px sans-serif":this.size+"px "+this.name;b.context.textBaseline="top";b.context.fillStyle="rgb("+this.color[0]+","+this.color[1]+","+this.color[2]+")";b.context.fillText(this.text,f[0],f[1])};this.fontFakeSurface.prototype.get_rect=function(){var b=document.createElement("canvas").getContext("2d");b.font=null==this.name?this.size+"px sans-serif":this.size+"px "+this.name;b.textBaseline="top";b.fillStyle="rgb("+this.color[0]+","+this.color[1]+
","+this.color[2]+")";b=[0,0,Math.max(b.measureText(this.text).width,1),this.size];b.left=0;b.top=0;b.right=b[2];b.bottom=b[3];return b}},event:[]},random={random:function(){return Math.random()},randint:function(g,l){return parseInt(this.random()*(l-g+1)+g)},choice:function(g){return g[this.randint(0,g.length-1)]}};function SystemExit(){}var sys={exit:function(){throw new SystemExit;}},QUIT=0,KEYDOWN=1,K_ESCAPE=0,K_SPACE=1,K_RETURN=2,K_s=3,RESIZE=2;
addEventListener("load",function(){function g(){pygame.event.push({type:RESIZE})}keyboard.bind("escape",function(b){pygame.event.push({type:KEYDOWN,key:K_ESCAPE});b.preventDefault()});keyboard.bind("space",function(b){pygame.event.push({type:KEYDOWN,key:K_SPACE});b.preventDefault()});keyboard.bind("enter",function(b){pygame.event.push({type:KEYDOWN,key:K_RETURN});b.preventDefault()});keyboard.bind("s",function(b){pygame.event.push({type:KEYDOWN,key:K_s});b.preventDefault()});var l=new Hammer(document.body);
l.on("tap",function(){pygame.event.push({type:KEYDOWN,key:K_SPACE})});l.on("press",function(){pygame.event.push({type:KEYDOWN,key:K_RETURN})});l.on("swiperight",function(){pygame.event.push({type:KEYDOWN,key:K_s})});addEventListener("resize",g);g()});
addEventListener("load",function(){function g(){(function V(){var g=new pygame.time.Clock,C=new pygame.font.Font(null,16),J=C.render("Tap, Press, Swipe!",!0,e),W=C.render("Colddown",!0,a),ba=J.get_rect(),x=C.render("Silver Bullets: ",!0,e),fa=x.get_rect(),E=0,S=0,M=!1,Y=3,T=new pygame.Surface([64,b]);T.fill(e);for(var p=[],G=0;G<l;G+=64)p.push([G,b-16]);var D=[],H=[],L=0,ca=0,X="",ha="A Great Wall!;Ouch!;Bang!;What A Nasty Scar!;Watch Out!;No Way!;Hurt!".split(";"),da="Eaten by Ant!;Full Stomache! --Ant;Nothing Left;Ants Are Celebrating;Who Bit Me!;Standing at the Bottom of the Food Chain".split(";"),
U=C.render("Tap to Run!",!0,e),A=!0;(function aa(){if(A){A=!1;0<L&&--L;M&&(ca+=1);M&&(p.forEach(function(a){a[0]+=-4}),0>p[0][0]+64&&p.shift());if(p[p.length-1][0]+64<l){var r=random.random();if(.98<r){var q=p[p.length-1];p.push([p[p.length-1][0]+64,b+32]);.995<r&&p.push([p[p.length-1][0]+64,b+32]);p.push([p[p.length-1][0]+64,q[1]])}else q=null,q=p[p.length-1][1]>=b-32?[0,-1]:64>=p[p.length-1][1]?[0,1]:[-1,0,1],p.push([p[p.length-1][0]+64,p[p.length-1][1]+32*random.choice(q)]),.05>r&&D.push([p[p.length-
1][0]+random.randint(0,32),p[p.length-1][1]-16,random.choice(f),p[p.length-1][0]+4])}for(var G=!1,r=[],q=0;q<p.length;++q){var w=p[q];(100>=w[0]&&100<=w[0]+64||132>=w[0]&&132<=w[0]+64)&&r.push(w);if(2==r.length)break}var N=-32;r.forEach(function(a){a[1]<b-N&&(N=b-a[1])});E+32>b-N?(G=!0,X=random.choice(ha)):E+32+S+1>=b-N?(E=b-N-32,S=0):M&&(S+=1,E+=S);for(r=0;r<H.length;++r){for(var q=H[r],w=!1,K=0;K<D.length;++K){var I=D[K],B=q[0],v=I[0],y=q[1],R=I[1],F=!0;B>=v&&B>=v+16?F=!1:B<=v&&B+8<=v?F=!1:y>=R&&
y>=R+16?F=!1:y<=R&&y+8<=R&&(F=!1);if(F){D.splice(D.indexOf(I),1);H.splice(H.indexOf(q),1);w=!0;Y+=2;break}}if(!w){for(K=0;K<p.length;++K)if(y=p[K],I=q[0],B=y[0],v=q[1],y=y[1],R=b,F=!0,I>=B&&I>=B+64?F=!1:I<=B&&I+8<=B?F=!1:v>=y&&v>=y+R?F=!1:v<=y&&v+8<=y&&(F=!1),F){H.splice(H.indexOf(q),1);w=!0;break}w||(q[0]+=16)}}D.forEach(function(a){a[3]-=4;a[0]+=a[2];a[0]<a[3]?a[2]=f[1]:a[0]+16>a[3]+64&&(a[2]=f[0]);var b=a[0];a=a[1];var d=E,e=!0;100<=b&&132<=b?e=!1:100>=b&&100>=b+16?e=!1:a>=d&&a>=d+32?e=!1:a<=d&&
a+16<=d&&(e=!1);e&&(G=!0,X=random.choice(da))});var P=!1;pygame.event.get().forEach(function(a){if(a.type==QUIT)sys.exit();else if(a.type==KEYDOWN)a.key==K_ESCAPE?sys.exit():a.key==K_SPACE?(M=!0,E+32==b-N&&(S=-12)):a.key==K_RETURN?M&&0==L&&(m.fill(d),pygame.display.update(),p.forEach(function(a){a[1]=b-16}),D=[],L=960,pygame.time.wait(1E3,aa),A=P=!0):a.key==K_s&&M&&0<Y&&(--Y,H.push([132,E+32-16]));else if(a.type==RESIZE){var e=m.get_rect();pygame.display.resize([innerWidth,innerHeight]);l=innerWidth;
b=innerHeight;p.forEach(function(a){a[1]=Math.max(32,a[1]-e.bottom+b)});E=Math.max(0,E-e.bottom+b);H.forEach(function(a){a[1]=Math.max(16,a[1]-e.bottom+b)});D.forEach(function(a){for(var b=0;b<p.length;++b)if(a[3]==p[b][0]){a[1]=p[b][1]-16;break}})}});if(!P){m.fill(a);k.fill(a);m.blit(J,[l-ba.right,0]);k.blit(J,[l-ba.right,0]);m.blit(C.render("fps: "+Math.floor(g.get_fps())+" Score: "+ca,!1,e),[0,0]);k.blit(C.render("fps: "+Math.floor(g.get_fps())+" Score: "+ca,!1,e),[0,0]);r=new pygame.Surface([Math.max(Math.floor(l/
32/30*L),1),16]);r.fill(e);m.blit(r,[0,16]);k.blit(r,[0,16]);m.blit(W,[0,16]);k.blit(W,[0,16]);m.blit(x,[0,32]);k.blit(x,[0,32]);for(r=0;r<Y;++r)m.blit(t,[fa.right+12*r,32+Math.floor(8)-Math.floor(4)]),k.blit(t,[fa.right+12*r,32+Math.floor(8)-Math.floor(4)]);m.blit(z,[100,E]);k.blit(z,[100,E]);p.forEach(function(a){m.blit(T,a);k.blit(T,[a[0]+Math.floor(-2),a[1]])});D.forEach(function(a){m.blit(u,a);k.blit(u,a)});H.forEach(function(a){m.blit(t,a);k.blit(t,[a[0]+Math.floor(8),a[1]])});M||(m.blit(U,
[Math.floor(l/2)-Math.floor(U.get_rect().right/2),Math.floor(b/2)-Math.floor(U.get_rect().bottom/2)]),k.blit(U,[Math.floor(l/2)-Math.floor(U.get_rect().right/2),Math.floor(b/2)-Math.floor(U.get_rect().bottom/2)]));pygame.display.update();var ea=!0;G?(r=(new pygame.font.Font(null,128)).render("\u2620",!0,d),q=C.render(X,!0,d),w=C.render("Press Space? Begin again.",!0,e),m.blit(r,[Math.floor(l/2)-Math.floor(r.get_rect().right/2),Math.floor(b/2)-Math.floor(r.get_rect().bottom/2)]),m.blit(q,[Math.floor(l/
2)-Math.floor(q.get_rect().right/2),Math.floor(b/2)+Math.floor(r.get_rect().bottom/2)]),m.blit(w,[Math.floor(l/2)-Math.floor(w.get_rect().right/2),Math.floor(b/2)+Math.floor(r.get_rect().bottom/2)+q.get_rect().bottom]),pygame.display.update(),function Q(){pygame.event.get().forEach(function(a){a.type==QUIT?sys.exit():a.type==KEYDOWN?(a.key==K_ESCAPE&&sys.exit(),a.key==K_SPACE&&(ea=!1)):pygame.event.push(a)});ea?pygame.time.wait(1E3,Q):V()}()):ea?g.tick(60,aa):V()}}else m.blit(k,[0,0]),pygame.display.update(),
A=!0,g.tick(60,aa)})()})()}var l=800,b=600,f=[-8,0],a=[0,0,0],e=[255,255,255],d=[255,0,0];pygame.init();var m=pygame.display.set_mode([l,b]),k=new pygame.Surface([l,b]),J=3,z,u,t;pygame.image.load("ranger.gif",function(a){z=a;0==--J&&g()});pygame.image.load("antman.gif",function(a){u=a;0==--J&&g()});pygame.image.load("shoot.gif",function(a){t=a;0==--J&&g()})});
